language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
  - website/node_modules
branches:
  only:
  - master
  - next
  - v0.11.0
install:
- git fetch --unshallow --all
- yarn global add codecov
- yarn
script:
- yarn run test && codecov
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "master" ]; then exit
  0; fi
- git config --global user.email "kroach.work@gmail.com"
- git config --global user.name "Kyle Roach"
- echo "machine github.com login iroachie password $GITHUB_TOKEN" > ~/.netrc
- cd website && yarn && GIT_USER=iroachie yarn run publish-gh-pages

