coverage:
  status:
    project:
      default: off
      base:
        paths:
          - packages/base/*
      themed:
        paths:
          - packages/themed/*
        target: 80%
        flags: themed
      universe:
        paths:
          - packages/universe/*
        target: 80%
        flags: universe

comment:
  require_changes: true
