name: Build and Deploy docs
on:
  push:
    branches:
      - next
    paths:
      - "website/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy Docs
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - name: Install dependencies
        run: yarn install
      - name: Cache website dependencies
        uses: actions/cache@v2
        with:
          path: website/.yarn/cache
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - name: Install website dependencies
        run: yarn install
        working-directory: website
      - name: Build 🔧
        run: yarn docs-build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: "React Native Elements CI"
          user_email: "react-native-elements-ci@users.noreply.github.com"
          cname: reactnativeelements.com
