name: Expo Default Channel Preview CI

on:
  push:
    branches:
      - "next"
    paths-ignore:
      - "website/**"
      - "scripts/**"

jobs:
  publish:
    defaults:
      run:
        working-directory: example
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: 🚀 Publish preview
        run: expo publish --non-interactive
