name: Test & Coverage
on:
  push:
  pull_request:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        run: |
          yarn global add codecov
          yarn
      - run: yarn lint
      - run: yarn typescript
      - run: yarn prettier
      - run: yarn test && npx codecov --disable=gcov
