name: Test & Coverage
on:
  push:
  pull_request:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: rne-tests
        with:
          path: node_modules
          key: ${{ runner.os }}-tests-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-tests-
      - name: Install
        if: steps.rne-tests.outputs.cache-hit != 'true' # Over here!
        run: |
          yarn global add codecov
          yarn
      - name: Testing
        run: |
          yarn lint
          yarn build
          yarn test && npx codecov --disable=gcov
